### ISSUE TITLE
naming issue?

### ISSUE THREAD

**Issue by randomwangran** [WenjieZ/2019-nCoV#1]
I think we are playing the same transport equation, so

`python/sir.ipynb`

should be 

`python/seir.ipynb
`

Ref
https://github.com/yijunwang0805/YijunWang/issues/2

**Comment by yijunwang0805** [comment]
Hi randomwangran, 

I came from the *mentioned mentioned* issue above. Both `SIR` and `SEIR` models are popular epidemic model. In this respository, Wenjie uses the `SIR` model

A good reference is posted on Zhihu regarding these models [model](https://blog.csdn.net/arcers/article/details/104238668)

**Comment by randomwangran** [comment]
@yijunwang0805 

I am now relax.

The `csdn` artile is useful because my mother lanuage is Chinese.

Thanks for sharing.

Now I want to learn more about `SIR` or `SEIR`. I will visit your website to learn more and possibly introduce you to my friends who want to study this as well.
